---

## Configure misc stuff on the proxmox host system

# proxmox disable enterprise repo
- name: Host > disable/enable proxmox enterprise repo
  apt_repository:
    repo: deb https://enterprise.proxmox.com/debian jessie pve-enterprise
    state: "{{ 'present' if proxmoxy_host_repo_enterprise else 'absent' }}"
    filename: pve-enterprise

- name: enable/disable proxmox no-subscription repo
  apt_repository:
    repo: deb http://download.proxmox.com/debian jessie pve-no-subscription
    state: "{{ 'present' if proxmoxy_host_repo_nosubs else 'absent' }}"
    filename: pve-no-subscription


  # suggestion for firewall
  #   - 'xt_tcpudp'
  # - 'xt_multiport'
- name: Host > load additional kernel modules at boot
  lineinfile:
    dest: /etc/modules-load.d/{{ item.key }}.conf
    regexp: "^{{ item.value }}"
    line: "{{ item.value }}"
    state: present
    create: yes
  with_dict: "{{ proxmoxy_host_modules }}"

  - name: Host > modprobe kernel modules now
    modprobe: name='{{ item.value }}'
  with_dict: "{{ proxmoxy_host_modules }}"


- name: Host > remove proxmox ui no-subscription warning message
  lineinfile:
    path: /usr/share/pve-manager/ext6/pvemanagerlib.js
    regexp: "(\\s*if \\(data.status !== 'Active')(\\) {)"
    line: '\1 && false\2'
    backrefs: yes
  when: proxmoxy_host_remove_nosubnag

- name: Host > enable tun/tap device in lxc
  lineinfile:
    dest: /etc/lxc/default.conf
    regexp: "^lxc.cgroup.devices.allow"
    line: "lxc.cgroup.devices.allow = c 10:200 rwm"
    state: present
  when: proxmoxy_host_tuntap
