---
# Host system
- include: host.yml
  tags:
    - proxmoxy
    - dev

# Templates
- include: templates.yml
  tags:
    - proxmoxy

# Permissions
- include: permission.yml
  tags:
    - proxmoxy

# # Storage
- include: storage.yml
  tags:
    - proxmoxy

# Provisioning
- include: prov.yml
  tags:
    - proxmoxy
